# Generated by Django 4.2.5 on 2023-09-08 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Say hello with python', 'Say hello with python'), ('Arithmetic Operators - Sum', 'Arithmetic Operators - Sum'), ('Loops', 'Loops')], max_length=100)),
                ('problem', models.TextField()),
                ('point', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('beginner', 'beginner'), ('medium', 'medium'), ('difficult', 'difficult')], max_length=50)),
                ('language', models.CharField(choices=[('python', 'python'), ('javasprits', 'javasprits'), ('C++', 'C++')], max_length=50)),
                ('input', models.CharField(blank=True, max_length=100)),
                ('expected_output', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
