# Generated by Django 4.2.5 on 2023-09-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='expected_output',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
